import mcpi.block as block
from mcpi.block import Block
block_materials = {
	"AIR": Block(0),
	"STONE": Block(1),
	"GRASS": Block(2),
	"DIRT": Block(3),
	"COBBLESTONE": Block(4),
	"WOOD PLANKS": Block(5),
	"SAPLING": Block(6),
	"BEDROCK": Block(7),
	"WATER FLOWING": Block(8),
	"WATER": Block(8),
	"WATER STATIONARY": Block(9),
	"LAVA FLOWING": Block(10),
	"LAVA": Block(10),
	"LAVA STATIONARY": Block(11),
	"SAND": Block(12),
	"GRAVEL": Block(13),
	"GOLD ORE": Block(14),
	"IRON ORE": Block(15),
	"COAL ORE": Block(16),
	"WOOD": Block(17),
	"LEAVES": Block(18),
	"GLASS": Block(20),
	"LAPIS LAZULI ORE": Block(21),
	"LAPIS LAZULI BLOCK": Block(22),
	"SANDSTONE": Block(24),
	"BED": Block(26),
	"RAIL POWERED": Block(27),
	"RAIL DETECTOR": Block(28),
	"COBWEB": Block(30),
	"GRASS TALL": Block(31),
	"DEAD BUSH": Block(32),
	"WOOL": Block(35),
	"FLOWER YELLOW": Block(37),
	"FLOWER CYAN": Block(38),
	"MUSHROOM BROWN": Block(39),
	"MUSHROOM RED": Block(40),
	"GOLD BLOCK": Block(41),
	"IRON BLOCK": Block(42),
	"STONE SLAB DOUBLE": Block(43),
	"STONE SLAB": Block(44),
	"BRICK BLOCK": Block(45),
	"TNT": Block(46),
	"BOOKSHELF": Block(47),
	"MOSS STONE": Block(48),
	"OBSIDIAN": Block(49),
	"TORCH": Block(50),
	"FIRE": Block(51),
	"STAIRS WOOD": Block(53),
	"CHEST": Block(54),
	"DIAMOND ORE": Block(56),
	"DIAMOND BLOCK": Block(57),
	"CRAFTING TABLE": Block(58),
	"FARMLAND": Block(60),
	"FURNACE INACTIVE": Block(61),
	"FURNACE ACTIVE": Block(62),
	"SIGN STANDING": Block(63),
	"DOOR WOOD": Block(64),
	"LADDER": Block(65),
	"RAIL": Block(66),
	"STAIRS COBBLESTONE": Block(67),
	"SIGN WALL": Block(68),
	"DOOR IRON": Block(71),
	"REDSTONE ORE": Block(73),
	"TORCH REDSTONE": Block(76),
	"SNOW": Block(78),
	"ICE": Block(79),
	"SNOW BLOCK": Block(80),
	"CACTUS": Block(81),
	"CLAY": Block(82),
	"SUGAR CANE": Block(83),
	"FENCE": Block(85),
	"PUMPKIN": Block(86),
	"NETHERRACK": Block(87),
	"SOUL SAND": Block(88),
	"GLOWSTONE BLOCK": Block(89),
	"LIT PUMPKIN": Block(91),
	"STAINED GLASS": Block(95),
	"BEDROCK INVISIBLE": Block(95),
	"TRAPDOOR": Block(96),
	"STONE BRICK": Block(98),
	"GLASS PANE": Block(102),
	"MELON": Block(103),
	"FENCE GATE": Block(107),
	"STAIRS BRICK": Block(108),
	"STAIRS STONE BRICK": Block(109),
	"MYCELIUM": Block(110),
	"NETHER BRICK": Block(112),
	"FENCE NETHER BRICK": Block(113),
	"STAIRS NETHER BRICK": Block(114),
	"END STONE": Block(121),
	"WOODEN SLAB": Block(126),
	"STAIRS SANDSTONE": Block(128),
	"EMERALD ORE": Block(129),
	"RAIL ACTIVATOR": Block(157),
	"LEAVES2": Block(161),
	"TRAPDOOR IRON": Block(167),
	"FENCE SPRUCE": Block(188),
	"FENCE BIRCH": Block(189),
	"FENCE JUNGLE": Block(190),
	"FENCE DARK OAK": Block(191),
	"FENCE ACACIA": Block(192),
	"DOOR SPRUCE": Block(193),
	"DOOR BIRCH": Block(194),
	"DOOR JUNGLE": Block(195),
	"DOOR ACACIA": Block(196),
	"DOOR DARK OAK": Block(197),
	"GLOWING OBSIDIAN": Block(246),
	"NETHER REACTOR CORE": Block(247)
	}